development: &defaults
  adapter: postgresql
  encoding: unicode
  database: chat_room_websocket_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test: &test
  <<: *defaults
  database: chat_room_websocket_test

production:
  database: chat_room_websocket_production
  <<: *defaults
