# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8681bbc0ae143341d2d4bed8c321ad3b13acfcc2778a3cd59b5879db76e21fd426c51b564fe4ddcb9bbf82db9cbdde26b36d3710c131b11ba8cbcc2f07d7e01f

test:
  secret_key_base: 2819404fc9d3d220748cb342bfb6a72cc8563570c6c3badc48a6de5f1f270adad6fe0f2d7919900ee32e7426c1af65c98c89f1e4c1b7838388e44bc61cc8ab7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
